version: '3.8'

services:
  myxampp:
    build: .
    container_name: myXampp8
    ports:
      - "${PORT_SSH}:22"
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
      - "${PORT_MYSQL}:3306"
    volumes:
      - "./www:/www"
      - "./log/apache:/var/log/apache2"
      - "./log/mysql:/var/log/mysql"
      - "./config:/opt/lampp/apache2/conf.d"
      - "myXdb:/opt/lampp/var/mysql"
    networks:
      - myXnet
    restart: always

volumes:
  myXdb:
networks:
  myXnet:
