services:
  myxampp:
    build: .
    image: myxampp8:6.3
    container_name: myXampp8
    ports:
      - "${PORT_SSH}:22"
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    volumes:
      - "./www:/www"
      - "./config/apache:/opt/lampp/apache2/conf.d" # Configuraciones adicionales Apache
      - "./config/php/php.ini:/opt/lampp/etc/php.ini" # Monta tu php.ini personalizado
      - "./config/php/conf.d:/opt/lampp/etc/php.d" # Configuraciones adicionales PHP
      - "./log/apache:/var/log/apache2"
      - "./log/mysql:/var/log/mysql"
      - "./log/lampp:/opt/lampp/logs"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    networks:
      myXnet:
    depends_on:
      - db
      - node

  db:
    image: mariadb:11.5
    container_name: myDb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${PORT_MARIADB}:3306"
    volumes:
      - ./db/mariadb:/var/lib/mysql
    restart: always
    networks:
      myXnet:


  node:
    image: node:18-alpine
    container_name: myNode
    working_dir: /app
    volumes:
      - ./www:/app
    command: "tail -f /dev/null"
    restart: always
    networks:
      myXnet:


networks:
  myXnet:
    driver: bridge
