services:
  myxampp:
    build: .
    image: myxampp8:3.0
    container_name: myXampp8
    ports:
      - "${PORT_SSH}:22"
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    volumes:
      - "./www:/www"
      - "./config:/opt/lampp/apache2/conf.d"
      - "./log/apache:/var/log/apache2"
      - "./log/mysql:/var/log/mysql"
    networks:
      - myXnet
    restart: always
    depends_on:
      - db
      - node

  db:
    image: mariadb:11.5
    container_name: myDb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - myXnet
    restart: always

  node:
    image: node:18-alpine
    container_name: myNode
    working_dir: /app
    volumes:
      - ./www:/app
    networks:
      - myXnet
    command: "tail -f /dev/null"

networks:
  myXnet:
